#:schema node_modules/wrangler/config-schema.json
name = "daily-calorie-log"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "daily-calorie-db"
database_id = "764b12ff-b731-4366-b46b-1da615b5e78b"
